In [1]:
import os
import gc
import sys
import glob
import numpy as np
import pandas as pd
import netCDF4 as nc
from datetime import datetime, timedelta
from matplotlib.cm import get_cmap
import matplotlib.pyplot as plt
from matplotlib import cm
from matplotlib import colors
import matplotlib.ticker as mticker

In [2]:
file_name = "/g/data/w97/mm3972/scripts/PLUMBER2/LSM_VPD_PLUMBER2/txt/process3_output/curves/raw_data_Qle_VPD_hourly_RM16_DT_EF_model_0-0.2.csv"
var_input = pd.read_csv(file_name)

In [3]:
var_input

,Unnamed: 0.1,Unnamed: 0,time,model_CABLE,CABLE_EF,model_CABLE-POP-CN,CABLE-POP-CN_EF,model_CHTESSEL_Ref_exp1,CHTESSEL_Ref_exp1_EF,model_CLM5a,...,JULES_GL9_withLAI_VPD_caused,MATSIRO_VPD_caused,MuSICA_VPD_caused,NASAEnt_VPD_caused,NoahMPv401_VPD_caused,ORC2_r6593_VPD_caused,ORC3_r8120_VPD_caused,QUINCY_VPD_caused,STEMMUS-SCOPE_VPD_caused,obs_VPD_caused
0,12,12,2010-01-01 06:30:00,NaN,0.526731,NaN,0.416425,NaN,0.543061,8.518562,...,10.227377,10.385898,4.020703,1.889827,11.000356,10.992177,10.743625,2.127346,9.735119,NaN
1,13,13,2010-01-01 07:00:00,NaN,0.507929,NaN,0.420786,NaN,0.485329,NaN,...,8.000010,8.531827,2.241691,6.301694,9.657070,9.753063,9.547667,1.383695,8.620071,NaN
2,14,14,2010-01-01 07:30:00,NaN,0.529003,NaN,0.336133,NaN,0.457484,NaN,...,10.938145,10.905654,-1.554748,11.868923,12.584963,12.437191,12.300113,2.200761,10.629994,10.872018
3,15,15,2010-01-01 08:00:00,NaN,0.613327,NaN,0.370076,NaN,0.477366,NaN,...,20.460072,17.555187,-0.309595,14.055197,24.315805,23.851703,23.839046,5.345618,21.114932,24.013982
4,16,16,2010-01-01 08:30:00,NaN,0.651370,NaN,0.434876,NaN,0.510675,NaN,...,47.200144,37.047239,18.579933,3.133893,46.856123,61.380357,61.155016,12.514902,53.895175,58.251754
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6120923,17120407,17120407,2002-12-31 16:00:00,75.12253,0.162078,68.249344,0.167131,66.584150,0.176478,NaN,...,37.653971,61.841719,43.190857,41.203304,47.686253,19.467074,22.450989,83.967847,89.398495,50.273151
6120924,17120408,17120408,2002-12-31 16:30:00,74.54569,0.198019,NaN,0.202175,57.032925,0.186982,NaN,...,34.505231,58.822839,50.198005,50.729871,45.391207,18.619200,20.430215,80.221642,87.824709,222.834801
6120925,17120409,17120409,2002-12-31 17:00:00,NaN,0.222832,NaN,0.257596,NaN,0.217206,NaN,...,30.924530,54.662562,53.693862,60.250922,43.578942,18.584285,18.916732,78.282126,85.633620,120.377388
6120926,17120410,17120410,2002-12-31 17:30:00,NaN,0.226764,NaN,0.356935,NaN,0.257973,NaN,...,26.298167,48.546225,31.092234,56.241494,39.431854,16.179787,16.483577,66.960058,78.213799,18.786880
6120927,17120411,17120411,2002-12-31 18:00:00,NaN,0.201706,NaN,0.542712,NaN,0.378839,NaN,...,21.614586,39.453844,28.516545,52.176860,35.636750,15.081853,14.836113,57.173369,65.953442,5.686850

In [4]:
var_input.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'time', 'model_CABLE', 'CABLE_EF',
       'model_CABLE-POP-CN', 'CABLE-POP-CN_EF', 'model_CHTESSEL_Ref_exp1',
       'CHTESSEL_Ref_exp1_EF', 'model_CLM5a',
       ...
       'JULES_GL9_withLAI_VPD_caused', 'MATSIRO_VPD_caused',
       'MuSICA_VPD_caused', 'NASAEnt_VPD_caused', 'NoahMPv401_VPD_caused',
       'ORC2_r6593_VPD_caused', 'ORC3_r8120_VPD_caused', 'QUINCY_VPD_caused',
       'STEMMUS-SCOPE_VPD_caused', 'obs_VPD_caused'],
      dtype='object', length=114)

In [5]:
model_list = ['model_CABLE', 'model_CABLE-POP-CN',
                             'model_CHTESSEL_Ref_exp1', 'model_CLM5a', 'model_GFDL',
                             'model_JULES_GL9', 'model_JULES_GL9_withLAI',
                             'model_MATSIRO', 'model_MuSICA', 'model_NASAEnt',
                             'model_NoahMPv401', 'model_ORC2_r6593',
                             'model_ORC3_r8120', 'model_QUINCY',
                             'model_STEMMUS-SCOPE', 'obs']

In [ ]:
subset            = ['VPD', 'Rnet', 'Wind', 'Tair', 'Psurf']
var_input[subset] = var_input[subset].where(~var_input[subset].isna().any(axis=1), other=np.nan)