### Notes:
I set the day at least one time step has nan in Qle or Qh to have a daily EF nan, and set the day's EF as nan for all models/obs if one of them is EF.

In [11]:
import os
import gc
import sys
import glob
import numpy as np
import pandas as pd
import netCDF4 as nc
from datetime import datetime, timedelta
from matplotlib.cm import get_cmap
import matplotlib.pyplot as plt
from matplotlib import cm
from matplotlib import colors
import matplotlib.ticker as mticker
from copy import deepcopy

In [12]:
# To use PLUMBER2_GPP_common_utils, change directory to where it exists
os.chdir('/g/data/w97/mm3972/scripts/PLUMBER2/LSM_VPD_PLUMBER2')
from PLUMBER2_VPD_common_utils import *

In [13]:
# Define a custom function for aggregation
# Set the grouped bin as nan if one time step in this day is nan
def custom_agg(series):
    if series.isnull().any():
        return np.nan
    else:
        return series.mean()

In [14]:
site_names, IGBP_types, clim_types, model_names = load_default_list()
X_day     = 1
use_Rnet  = False

In [15]:
# Read Qle_input and Qh_input
Qle_input = pd.read_csv('./txt/process1_output/Qle_all_sites.csv',
                        na_values=[''],
                        usecols=['time', 'month', 'site_name', 'model_CABLE', 'model_CABLE-POP-CN',
                                 'model_CHTESSEL_Ref_exp1', 'model_CLM5a', 'model_GFDL',
                                 'model_JULES_GL9', 'model_JULES_GL9_withLAI', 'model_MATSIRO',
                                 'model_MuSICA', 'model_NASAEnt', 'model_NoahMPv401', 'model_ORC2_r6593',
                                 'model_ORC3_r8120', 'model_QUINCY', 'model_STEMMUS-SCOPE', 'obs'])

if use_Rnet:
    ### no 'model_JULES_GL9'
    Rnet_input = pd.read_csv('./txt/process1_output/Rnet_all_sites.csv',
                           na_values=[''],
                           usecols=['time', 'month', 'site_name', 'model_CABLE', 'model_CABLE-POP-CN',
                                    'model_CHTESSEL_Ref_exp1', 'model_CLM5a', 'model_GFDL',
                                    'model_JULES_GL9', 'model_JULES_GL9_withLAI', 'model_MATSIRO',
                                    'model_MuSICA', 'model_NASAEnt', 'model_NoahMPv401', 'model_ORC2_r6593',
                                    'model_ORC3_r8120', 'model_QUINCY', 'model_STEMMUS-SCOPE', 'obs'])

    # Check for 'time' column
    if 'time' not in Qle_input.columns or 'time' not in Rnet_input.columns:
        raise ValueError("The input files do not contain a 'time' column")

    # Extract 'year' and 'day' from 'time' column
    Qle_input['year'] = Qle_input['time'].apply(lambda x: datetime.strptime(x, "%Y-%m-%d %H:%M:%S").year)
    Qle_input['day']  = Qle_input['time'].apply(lambda x: datetime.strptime(x, "%Y-%m-%d %H:%M:%S").day)
    Rnet_input['year']= Qle_input['year'][:]
    Rnet_input['day'] = Qle_input['day'][:]
    
    # Replace -9999 with NaN
    Qle_input.replace(-9999, np.nan, inplace=True)
    Rnet_input.replace(-9999, np.nan, inplace=True)

    # Drop 'time' column
    Qle_input.drop(columns=['time'], inplace=True)
    Rnet_input.drop(columns=['time'], inplace=True)
    
    '''
    Set the day's EF as nan if one time step is nan
    '''
    # Define grouping columns
    grouping_cols = ['year', 'month', 'day', 'site_name']

    # Get the list of columns to aggregate
    columns_to_aggregate = [col for col in Qle_input.columns if col not in grouping_cols]

    # Create the aggregation dictionary dynamically
    agg_dict = {col: custom_agg for col in columns_to_aggregate}

    daily_Qle = Qle_input.groupby(['year', 'month', 'day', 'site_name']).agg(agg_dict).reset_index()
    daily_Rnet= Rnet_input.groupby(['year', 'month', 'day', 'site_name']).agg(agg_dict).reset_index()
    
    
    # daily_Qle = Qle_input.groupby(['year', 'month', 'day', 'site_name']).mean().reset_index()
    # daily_Rnet= Rnet_input.groupby(['year', 'month', 'day', 'site_name']).mean().reset_index()
    
else:
    Qh_input = pd.read_csv('./txt/process1_output/Qh_all_sites.csv',
                           na_values=['-9999'],
                           usecols=['time', 'month', 'site_name', 'model_CABLE', 'model_CABLE-POP-CN',
                                    'model_CHTESSEL_Ref_exp1', 'model_CLM5a', 'model_GFDL',
                                    'model_JULES_GL9', 'model_JULES_GL9_withLAI', 'model_MATSIRO',
                                    'model_MuSICA', 'model_NASAEnt', 'model_NoahMPv401', 'model_ORC2_r6593',
                                    'model_ORC3_r8120', 'model_QUINCY', 'model_STEMMUS-SCOPE', 'obs'])

    # Check for 'time' column
    if 'time' not in Qle_input.columns or 'time' not in Qh_input.columns:
        raise ValueError("The input files do not contain a 'time' column")

    # Extract 'year' and 'day' from 'time' column
    Qle_input['year'] = Qle_input['time'].apply(lambda x: datetime.strptime(x, "%Y-%m-%d %H:%M:%S").year)
    Qle_input['day']  = Qle_input['time'].apply(lambda x: datetime.strptime(x, "%Y-%m-%d %H:%M:%S").day)
    Qh_input['year']  = Qle_input['year'][:]
    Qh_input['day']   = Qle_input['day'][:]
    
    # Replace -9999 with NaN
    Qle_input.replace(-9999, np.nan, inplace=True)
    Qh_input.replace(-9999, np.nan, inplace=True)

    # Drop 'time' column
    Qle_input.drop(columns=['time'], inplace=True)
    Qh_input.drop(columns=['time'], inplace=True)
    
    
    '''
    Set the day's EF as nan if one time step is nan
    '''
    # Define grouping columns
    grouping_cols = ['year', 'month', 'day', 'site_name']

    # Get the list of columns to aggregate
    columns_to_aggregate = [col for col in Qle_input.columns if col not in grouping_cols]

    # Create the aggregation dictionary dynamically
    agg_dict = {col: custom_agg for col in columns_to_aggregate}

    daily_Qle = Qle_input.groupby(['year', 'month', 'day', 'site_name']).agg(agg_dict).reset_index()
    daily_Qh  = Qh_input.groupby(['year', 'month', 'day', 'site_name']).agg(agg_dict).reset_index()
    
    # daily_Qle = Qle_input.groupby(['year', 'month', 'day', 'site_name']).mean().reset_index() 
    # daily_Qh  = Qh_input.groupby(['year', 'month', 'day', 'site_name']).mean().reset_index()

In [19]:
columns_to_aggregate

['model_CABLE',
 'model_CABLE-POP-CN',
 'model_CHTESSEL_Ref_exp1',
 'model_CLM5a',
 'model_GFDL',
 'model_JULES_GL9',
 'model_JULES_GL9_withLAI',
 'model_MATSIRO',
 'model_MuSICA',
 'model_NASAEnt',
 'model_NoahMPv401',
 'model_ORC2_r6593',
 'model_ORC3_r8120',
 'model_QUINCY',
 'model_STEMMUS-SCOPE',
 'obs']

In [20]:
daily_EF          = deepcopy(daily_Qle)
daily_EF_output   = deepcopy(daily_Qle)

for model_name in model_names['model_select_new']:
    if model_name == 'obs':
        head = ''
    else:
        head = 'model_'
        
    if use_Rnet:
        # qc_mask = (daily_Qle[head + model_name]<=800) & (daily_Qle[head + model_name]>=-300) & (daily_Rnet[head + model_name]<=2000) & (daily_Rnet[head + model_name]>=-1000)
        daily_EF.loc[:, head + model_name] = daily_Qle[head + model_name]/daily_Rnet[head + model_name]
    else:
        # qc_mask = (daily_Qle[head + model_name]<=800) & (daily_Qle[head + model_name]>=-300) & (daily_Qh[head + model_name]<=800) & (daily_Qh[head + model_name]>=-300)
        daily_EF.loc[:, head + model_name] = daily_Qle[head + model_name]/(daily_Qle[head + model_name]+daily_Qh[head + model_name])
    
    if X_day > 1:
        for site_name in site_names:
            site_mask = (daily_EF_smoothed['site_name']==site_name)

            # Calculate 5-day rolling mean of efficiency factor grouped by ['year', 'month', 'day', 'site_name']
            daily_EF_output.loc[site_mask, head + model_name] = daily_EF.loc[site_mask, head + model_name].rolling(window=X_day, min_periods=1).mean() 
    else:
        daily_EF_output = daily_EF

### Set the EF in a day is nan in any model/obs as nan for all models/obs

In [30]:
daily_EF_output

,year,month,day,site_name,model_CABLE,model_CABLE-POP-CN,model_CHTESSEL_Ref_exp1,model_CLM5a,model_GFDL,model_JULES_GL9,model_JULES_GL9_withLAI,model_MATSIRO,model_MuSICA,model_NASAEnt,model_NoahMPv401,model_ORC2_r6593,model_ORC3_r8120,model_QUINCY,model_STEMMUS-SCOPE,obs
0,1992,1.0,1,US-Ha1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1992,1.0,2,US-Ha1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1992,1.0,3,US-Ha1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1992,1.0,4,US-Ha1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1992,1.0,5,US-Ha1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
380035,2018,12.0,28,AU-Cum,0.589902,0.374115,0.558392,0.458786,0.729052,0.499830,0.488832,0.434229,0.457130,0.370613,0.541713,0.436962,0.462264,0.456100,0.556014,0.470660
380036,2018,12.0,29,AU-Cum,0.517104,0.321453,0.529832,0.446598,0.771161,0.461889,0.372495,0.419970,0.402845,0.328830,0.513570,0.413087,0.430876,0.430109,0.480912,0.455969
380037,2018,12.0,30,AU-Cum,0.455575,0.330731,0.520848,0.509643,0.851418,0.457481,0.340042,0.442610,0.493498,0.367213,0.519462,0.446993,0.484644,0.503197,0.480738,0.500235
380038,2018,12.0,31,AU-Cum,0.496408,0.417865,0.559526,0.632012,1.011225,0.520832,0.410139,0.544747,0.691640,0.473466,0.601347,0.533149,0.568147,0.646312,0.475834,0.567145
380039,2019,1.0,1,AU-Cum,2.358371,2.112991,1.314853,1.291753,-1.227866,1.045649,1.148426,2.320827,0.868974,2.980028,0.839949,0.678080,0.558176,1.033771,1.910136,3.468683

In [23]:
np.sum(np.isnan(daily_EF_output['obs'].values))

4998

In [24]:
model_names = columns_to_aggregate
daily_EF_output[model_names] = daily_EF_output[model_names].where(~daily_EF_output[model_names].isna().any(axis=1), other=np.nan)

In [34]:
remove_site=['AU-Rig','AU-Rob','AU-Whr','AU-Ync','CA-NS1','CA-NS2','CA-NS4','CA-NS5','CA-NS6', 
             'CA-NS7','CA-SF1','CA-SF2','CA-SF3','RU-Che','RU-Zot','UK-PL3','US-SP1',
             'AU-Wrr','CN-Din','US-WCr','ZM-Mon']
for site_name in site_names:
    site_mask = (daily_EF_output['site_name'] == site_name)
    lost_percent =  (np.sum(np.isnan(daily_EF_output.loc[site_mask, 'model_CABLE']))/len(daily_EF_output.loc[site_mask, 'model_CABLE']))*100
    # print(site_name,  np.sum(np.isnan(daily_EF_output.loc[site_mask, 'model_CABLE'])),lost_percent)
    if lost_percent == 100 and not site_name in  remove_site:
        print('lose ', site_name)

AR-SLu 3 0.819672131147541
AT-Neu 111 2.761881064941528
AU-ASM 114 4.4566067240031275
AU-Cow 417 19.02372262773723
AU-Cpr 17 0.6645817044566067
AU-Ctr 454 15.531987683886417
AU-Cum 114 5.200729927007299
AU-DaP 19 1.2995896032831737
AU-DaS 69 2.3605884365378036
AU-Dry 46 2.517788724685276
AU-Emr 17 2.3224043715846996
AU-GWW 28 1.532567049808429
AU-Gin 118 5.380756953944369
AU-How 652 11.897810218978103
AU-Lit 141 19.262295081967213
AU-Otw 2 0.27359781121751026
AU-Rig 16 0.729594163246694
AU-Rob 1462 100.0
AU-Sam 189 7.388584831899922
AU-Stp 161 5.508039685254875
AU-TTE 56 3.065134099616858
AU-Tum 16 0.2737382378100941
AU-Whr 125 17.076502732240435
AU-Wrr 732 100.0
AU-Ync 2558 100.0
BE-Bra 184 4.57825329684001
BE-Lon 59 1.6151108677799069
BE-Vie 247 3.7566539923954374
BR-Sa3 441 40.237226277372265
BW-Ma1 12 3.2697547683923704
CA-NS1 2 0.546448087431694
CA-NS2 1097 100.0
CA-NS4 5 0.6830601092896175
CA-NS5 5 0.6830601092896175
CA-NS6 1097 100.0
CA-NS7 732 100.0
CA-Qcu 376 20.58018609742748
CA-Qfo 26 1.016419077404222
CA-SF1 81 7.383773928896992
CA-SF2 18 1.6408386508659982
CA-SF3 184 16.773017319963536
CH-Cha 439 13.351581508515814
CH-Dav 309 4.699619771863118
CH-Fru 161 5.508039685254875
CH-Oe1 188 7.349491790461298
CN-Cha 21 1.9143117593436645
CN-Cng 14 1.912568306010929
CN-Dan 35 4.781420765027322
CN-Din 1097 100.0
CN-Du2 98 13.387978142076504
CN-HaM 63 8.618331053351573
CN-Qia 73 6.654512306289881
CZ-wet 85 2.907971262401642
DE-Bay 19 1.7335766423357664
DE-Geb 243 4.751662104028158
DE-Gri 205 5.100771336153271
DE-Hai 1251 26.33684210526316
DE-Kli 221 6.049822064056939
DE-Meh 28 2.552415679124886
DE-Obe 130 5.08209538702111
DE-Seh 15 1.367365542388332
DE-SfN 17 2.3255813953488373
DE-Tha 297 4.782608695652174
DE-Wet 124 6.787082649151614
DK-Fou 2 0.546448087431694
DK-Lva 27 3.6935704514363885
DK-Ris 5 0.6830601092896175
DK-Sor 251 3.8174904942965777
DK-ZaH 739 14.447702834799609
ES-ES1 101 3.4553540882654805
ES-ES2 79 10.807113543091655
ES-LMa 66 6.01640838650866
ES-LgS 27 7.377049180327869
ES-VDA 39 10.626702997275205
FI-Hyy 224 3.227200691543005
FI-Kaa 27 2.461257976298997
FI-Lom 195 17.775752051048315
FI-Sod 13 0.508209538702111
FR-Fon 92 2.798053527980535
FR-Gri 41 1.2469586374695865
FR-Hes 143 3.9145907473309607
FR-LBr 203 9.25672594619243
FR-Lq1 66 6.01640838650866
FR-Lq2 66 6.01640838650866
FR-Pue 158 2.8832116788321165
GF-Guy 1391 34.61059965165464
HU-Bug 3 0.2051983584131327
ID-Pag 207 28.317373461012313
IE-Ca1 3 0.27347310847766637
IE-Dri 9 0.8204193254329991
IT-Amp 102 6.976744186046512
IT-BCi 39 1.7791970802919708
IT-CA1 24 3.278688524590164
IT-CA2 10 1.366120218579235
IT-CA3 29 3.9617486338797816
IT-Col 35 1.1973999315771466
IT-Cpz 95 3.250085528566541
IT-Isp 21 2.8727770177838576
IT-LMa 22 3.0054644808743167
IT-Lav 99 2.7101012866137424
IT-MBo 281 7.690202517788725
IT-Mal 24 6.557377049180328
IT-Noe 109 2.7121174421497884
IT-Non 12 3.278688524590164
IT-PT1 14 1.912568306010929
IT-Ren 46 3.146374829001368
IT-Ro1 72 3.9408866995073892
IT-Ro2 90 3.5183737294761532
IT-SR2 20 2.7359781121751023
IT-SRo 155 4.241926655719759
JP-SMF 126 8.618331053351573
NL-Ca1 36 2.462380300957592
NL-Hor 745 50.95759233926128
NL-Loo 367 5.909822866344606
PL-wet 21 2.8688524590163933
PT-Esp 49 4.466727438468551
PT-Mi1 0 0.0
PT-Mi2 0 0.0
RU-Che 194 26.50273224043716
RU-Fyo 102 2.326642335766423
RU-Zot 10 2.73224043715847
SD-Dem 407 22.27695675971538
SE-Deg 377 25.786593707250343
UK-Gri 12 1.639344262295082
UK-Ham 24 6.539509536784741
UK-PL3 21 2.8727770177838576
US-AR1 52 4.740200546946217
US-AR2 108 14.774281805745554
US-ARM 157 4.296661193212917
US-Aud 7 0.6381039197812215
US-Bar 9 2.459016393442623
US-Bkg 113 15.45827633378933
US-Blo 102 3.98749022673964
US-Bo1 180 4.927456884752258
US-Cop 15 2.0519835841313268
US-FPe 165 6.450351837372947
US-GLE 13 0.5930656934306568
US-Goo 34 3.099361896080219
US-Ha1 7672 100.0
lose  US-Ha1
US-Ho1 160 4.8647005168744295
US-KS2 142 9.712722298221614
US-Los 80 2.4323502584372148
US-MMS 96 1.6424294268605648
US-MOz 33 4.514363885088919
US-Me2 119 2.5057906927774267
US-Me4 1467 80.25164113785557
US-Me6 71 4.856361149110807
US-Myb 59 4.035567715458276
US-NR1 187 3.1993156544054746
US-Ne1 648 16.123413784523514
US-Ne2 658 16.37223189848221
US-Ne3 340 8.459815874595671
US-PFa 573 7.842868874897345
US-Prr 28 2.552415679124886
US-SP1 1 0.273224043715847
US-SP2 156 8.533916849015318
US-SP3 184 8.39033287733698
US-SRG 16 0.7299270072992701
US-SRM 60 1.4929086837521772
US-Syv 471 18.412822517591867
US-Ton 37 0.7235041063746578
US-Tw4 13 3.551912568306011
US-Twt 9 0.49261083743842365
US-UMB 94 1.715328467153285
US-Var 9 0.17598748533437622
US-WCr 2923 100.0
US-Whs 32 1.2509773260359656
US-Wkg 43 1.1771147002463729
ZA-Kru 35 3.1905195989061075
ZM-Mon 367 100.0

### Save to daily values

In [ ]:
# Drop unnecessary columns from Qh_input
Qle_input.drop(columns=['model_CABLE', 'model_CABLE-POP-CN', 'model_CHTESSEL_Ref_exp1', 'model_CLM5a',
                       'model_GFDL', 'model_JULES_GL9', 'model_JULES_GL9_withLAI', 'model_MATSIRO',
                       'model_MuSICA', 'model_NASAEnt', 'model_NoahMPv401', 'model_ORC2_r6593',
                       'model_ORC3_r8120', 'model_QUINCY', 'model_STEMMUS-SCOPE', 'obs'], inplace=True)

Qle_input

In [ ]:
# Merge var_output back to Qh_input
var_output = pd.merge(Qle_input, daily_EF_output, on=['year', 'month', 'day', 'site_name'], how='left')

In [ ]:
# Save the processed data to a new CSV file
if use_Rnet:
    daily_Qle.to_csv(f'./txt/process2_output/Qle_all_sites_daily_mean.csv', index=False)
    daily_Rnet.to_csv(f'./txt/process2_output/Rnet_all_sites_daily_mean.csv', index=False)
    daily_EF.to_csv(f'./txt/process2_output/EF_all_sites_daily_mean_use_Rnet.csv', index=False)
    var_output.to_csv(f'./txt/process2_output/EF_all_sites_{X_day}_day_mean_use_Rnet.csv', index=False)
else:
    daily_Qle.to_csv(f'./txt/process2_output/Qle_all_sites_daily_mean.csv', index=False)
    daily_Qh.to_csv(f'./txt/process2_output/Qh_all_sites_daily_mean.csv', index=False)
    daily_EF.to_csv(f'./txt/process2_output/EF_all_sites_daily_mean.csv', index=False)
    var_output.to_csv(f'./txt/process2_output/EF_all_sites_{X_day}_day_mean.csv', index=False)